
title: ISPASS2023
email: arne.symons@kuleuven.be
description: >- # this means to ignore newlines until "baseurl:"
  Tutorial on HW Architecture-Mapping Design Space Exploration Framework for Deep Learning Accelerators.
#twitter_username: username
github_username: ZigZag-Project
minimal_mistakes_skin: default
search: false

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
#permalink: /:categories/:title/
#permalink: /tutorial/
#paginate_path: /tutorial/
#paginate: 5 # amount of posts to show
#aginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Arne Symons"
  avatar : "/assets/images/arne.jpg"
  bio    : "Arne Symons is a 3rd year Ph.D. researcher at MICAS - KU Leuven, Belgium. His research focuses on mapping optimisation of deep learning workloads onto specialized multi-core hardware accelerators employing layer-fused processing."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-microchip"
      url: "https://micas.be"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/"

header:
  image: /assets/images/leuven3.jpg
  
footer:
  links:
    # - label: "Twitter"
    #   icon: "fab fa-fw fa-twitter-square"
    #   url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ZigZag-Project/"
    # - label: "Instagram"
    #   icon: "fab fa-fw fa-instagram"
    #   url: "https://instagram.com/"

defaults:
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: splash
      author_profile: false
      
#category_archive:
#  type: liquid
#  path: /categories/
#tag_archive:
#  type: liquid
#  path: /tags/
